//Create a user
POST http://localhost:5001/users
Content-Type: application/json

{
    "name": "users",
    "email": "users@gmail.com",
    "password": "users",
    "confPassword": "users",
    "role": "users"
}

###
//get All Users
GET http://localhost:5001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NjgwNDkwLCJleHAiOjE3NDU2ODQwOTB9.J_zA63gzriAvrRFZ3Lh0vC_trGC6WADNrscwf3O9zcQ

###
//Get Single Users
GET http://localhost:5001/users/ad71feda-fc92-476b-bdc2-e670be7f347d

###
//Update Users
PATCH http://localhost:5001/users/c2c1b1d0-f640-4bc2-941d-f914a9f73c1c
Content-Type: application/json

{
    "name": "Tiaranisarsd",
    "email": "tiaranisars@gmail.com",
    "password": "admin",
    "confPassword": "admin",
    "role": "admin"
}

###
//Delete a Users
DELETE http://localhost:5001/users/7b42670f-20ad-4a9d-9324-7fccd4fcce42

###
// Login Users
POST http://localhost:5001/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###
// Login sebagai Users
POST http://localhost:5001/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###
GET http://localhost:5001/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

###
DELETE http://localhost:5001/logout


###
// Get All Pendaftaran
GET http://localhost:5001/pendaftaran
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

###
// Get Single Pendaftaran
GET http://localhost:5001/pendaftaran/2caf3000-8b13-4b6f-be34-a28a3ebcc181
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

###
// POST Data Pendaftaran
POST http://localhost:5001/pendaftaran
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

{
    "name": "test",
    "rw": 8,
    "lombaId": 1,
    "categoryId": 1
}

###
// UPDATE Data Pendaftaran
PATCH http://localhost:5001/pendaftaran/2caf3000-8b13-4b6f-be34-a28a3ebcc181
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

{
    "name": "testssss rw8 updated",
    "rw": 8,
    "lombaId": 1,
    "categoryId": 1
}

###
// Delete Data Pendaftaran
DELETE http://localhost:5001/pendaftaran/2caf3000-8b13-4b6f-be34-a28a3ebcc181
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI


###
// Get All Lomba
GET http://localhost:5001/lomba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

###
// Get All Category
GET http://localhost:5001/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

###
// POST Data Lomba
POST http://localhost:5001/lomba
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

{
    
    "lombaName": "Badminton"
}

###
// POST Data Category
POST http://localhost:5001/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

{
    
    "categoryName": "Single Putra",
    "lombaId": 1
}

###
//Update Lomba
PATCH http://localhost:5001/lomba/fe0beebe-95f9-4a9c-a4cc-dd50c95ec5d9
Content-Type: application/json

{
"lombaName": "test update"
}

###
//Update Category
PATCH http://localhost:5001/category/99d30b1b-23fa-48fc-88b4-944345ec101f
Content-Type: application/json

{
"categoryName": "Ganda Putra update"
}

###
//Delete Lomba
DELETE http://localhost:5001/lomba/4e535098-77d0-4dbb-a323-884aca705c97

###
//Delete Category
DELETE http://localhost:5001/category/6f7cc3e7-a2e7-4337-9812-20c351cebf52

###
//Category By Lomba
GET http://localhost:5001/category/lomba/1

###
// Get All Dashboard
GET http://localhost:5001/Dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM1ODY1LCJleHAiOjE3NDU3Mzk0NjV9.NOCFiMg6B290z5L-1dEHHMSsJhv8iOhoEHwPjeb2LnY

###
// Get Single Dashboard
GET http://localhost:5001/dashboard/112973ca-e0e2-4d00-b14c-acc63256cc8f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM1ODY1LCJleHAiOjE3NDU3Mzk0NjV9.NOCFiMg6B290z5L-1dEHHMSsJhv8iOhoEHwPjeb2LnY

###
// POST Data Dashboard
POST http://localhost:5001/Dashboard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM1ODY1LCJleHAiOjE3NDU3Mzk0NjV9.NOCFiMg6B290z5L-1dEHHMSsJhv8iOhoEHwPjeb2LnY

{
    "lombaId": 1,
    "imageUrl": "1720496226573-437123357.jpg",
    "categoryId": "1",
    "aturanLomba": "<p>tesst </p>"
}

###
//Update Data Dashboard
PATCH http://localhost:5001/Dashboard/545d1b55-2b02-4704-bfe0-3c706d3e3ea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM1ODY1LCJleHAiOjE3NDU3Mzk0NjV9.NOCFiMg6B290z5L-1dEHHMSsJhv8iOhoEHwPjeb2LnY

{

    "lombaId": 1,
    "imageUrl": "1720883725343-69949999.jpg",
    "categoryId": "[13, 14]",
    "aturanLomba": "<p>tesst updated 3 </p>"
}

###
//Delete Data Dashboard
DELETE http://localhost:5001/Dashboard/545d1b55-2b02-4704-bfe0-3c706d3e3ea

###
// Get All Banner
GET http://localhost:5001/Banner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NjU1MTkzLCJleHAiOjE3NDU2NTg3OTN9.G6NZuuRk93mto3XFQYf_K5l3U_sWDxVAxIAHf5Vs8t0

###
// Get Single banner
GET http://localhost:5001/banner/a94420e0-9e7d-4ea9-afe3-605b60cc88aa


###
// POST Data Banner
POST http://localhost:5001/Banner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NjU1MTkzLCJleHAiOjE3NDU2NTg3OTN9.G6NZuuRk93mto3XFQYf_K5l3U_sWDxVAxIAHf5Vs8t0

{

    "bannerName": "test 4",
    "imageBanner": "1720496226573-437123357.jpg"
}

###
// Update Data Banner
PATCH http://localhost:5001/banner/a94420e0-9e7d-4ea9-afe3-605b60cc88aa
Content-Type: application/json

{

    "bannerName": "test 1",
    "imageBanner": "1720962936493-392516406.jpg"
}

###
//Delete Data Banner
DELETE http://localhost:5001/Banner/gdvsdvsdfsf

###
// Get All Dokumentasi
GET http://localhost:5001/Dokumentasi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NjgwNDkwLCJleHAiOjE3NDU2ODQwOTB9.J_zA63gzriAvrRFZ3Lh0vC_trGC6WADNrscwf3O9zcQ

###
// Get Single Dokumentasi
GET http://localhost:5001/Dokumentasi/92223f36-7b5b-4500-ae84-2324025f8eee


###
// POST Data Dokumentasi
POST http://localhost:5001/Dokumentasi
Content-Type: application/json

{

    "kegiatanName": "test 3",
    "imageKegiatan": "1720496226573-437123357.jpg"
}

###
//Delete Data Dokuemntasi
DELETE http://localhost:5001/Dokumentasi/f03e3889-8615-409c-a641-c64c5829028e

###
// Get All Tentang Kegiatan
GET http://localhost:5001/TentangKegiatan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NjgwNDkwLCJleHAiOjE3NDU2ODQwOTB9.J_zA63gzriAvrRFZ3Lh0vC_trGC6WADNrscwf3O9zcQ

###
// Get Single TentangKegiatan
GET http://localhost:5001/TentangKegiatan/114f1f91-fd8b-4490-9752-cfdc1abbda17


###
// POST Data TentangKegiatan
POST http://localhost:5001/TentangKegiatan
Content-Type: application/json

{

    "judulKegiatan": "test 1",
    "image": "1720496226573-437123357.jpg",
    "tanggal": "12/07/2024",
    "keterangan": "test"
}

###
//Delete Data TentangKegiatan
DELETE http://localhost:5001/TentangKegiatan/114f1f91-fd8b-4490-9752-cfdc1abbda17