//Create a user
POST http://localhost:5001/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQwNjc1LCJleHAiOjE3NDU3NDQyNzV9.4EHmzTZ2hEzzee4AJDE5JgwwxlZ3xbz9e1vOp7oH1DQ

{
    "name": "users",
    "email": "users@gmail.com",
    "password": "users",
    "confPassword": "users",
    "role": "users"
}

###
//get All Users
GET http://localhost:5001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQyNDk1LCJleHAiOjE3NDU3NDYwOTV9.p7jxX7-ceyxVuT_w-f2Fi9bS-IfGji4vFHXDtCHfVoE

###
//Get Single Users
GET http://localhost:5001/users/5530adaa-7e6d-4f59-8e8c-c362f6779610
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQwNjc1LCJleHAiOjE3NDU3NDQyNzV9.4EHmzTZ2hEzzee4AJDE5JgwwxlZ3xbz9e1vOp7oH1DQ

###
//Update Users
PATCH http://localhost:5001/users/fbfec53e-89bb-434a-85c0-0a03907cf225
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQwNjc1LCJleHAiOjE3NDU3NDQyNzV9.4EHmzTZ2hEzzee4AJDE5JgwwxlZ3xbz9e1vOp7oH1DQ

{
    "name": "Tiaranisarsd",
    "email": "tiaranisars@gmail.com",
    "password": "admin",
    "confPassword": "admin",
    "role": "user"
}

###
//Delete a Users
DELETE http://localhost:5001/users/5530adaa-7e6d-4f59-8e8c-c362f6779610
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQwNjc1LCJleHAiOjE3NDU3NDQyNzV9.4EHmzTZ2hEzzee4AJDE5JgwwxlZ3xbz9e1vOp7oH1DQ

###
// Login Users
POST http://localhost:5001/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###
// Login sebagai Users
POST http://localhost:5001/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###
GET http://localhost:5001/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQyNDk1LCJleHAiOjE3NDU3NDYwOTV9.p7jxX7-ceyxVuT_w-f2Fi9bS-IfGji4vFHXDtCHfVoE

###
DELETE http://localhost:5001/logout


###
// Get All Pendaftaran
GET http://localhost:5001/pendaftaran
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM3MDA3LCJleHAiOjE3NDU3NDA2MDd9.lswKQ7NzZ3Iqs0ZG_ZJI6mQ5PZcTrPPD0MyPL6Jj0n4

###
// Get Single Pendaftaran
GET http://localhost:5001/pendaftaran/2caf3000-8b13-4b6f-be34-a28a3ebcc181
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

###
// POST Data Pendaftaran
POST http://localhost:5001/pendaftaran
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM3MDA3LCJleHAiOjE3NDU3NDA2MDd9.lswKQ7NzZ3Iqs0ZG_ZJI6mQ5PZcTrPPD0MyPL6Jj0n4

{
    "name": "test",
    "rw": 8,
    "lombaId": 1,
    "categoryId": 1
}

###
// UPDATE Data Pendaftaran
PATCH http://localhost:5001/pendaftaran/2caf3000-8b13-4b6f-be34-a28a3ebcc181
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI

{
    "name": "testssss rw8 updated",
    "rw": 8,
    "lombaId": 1,
    "categoryId": 1
}

###
// Delete Data Pendaftaran
DELETE http://localhost:5001/pendaftaran/2caf3000-8b13-4b6f-be34-a28a3ebcc181
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzMyMTU2LCJleHAiOjE3NDU3MzU3NTZ9.qfNRh__PE61ZPM73XPvnzsv5nLJCoOl-6toGVxUevqI


###
// Get All Lomba
GET http://localhost:5001/lomba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQzMzgxLCJleHAiOjE3NDU3NDY5ODF9.yDRCIg0IhOvCMbJ98jGQ6_PBS3NrXY9rrJLGpnl2huw

###
// Get All Category
GET http://localhost:5001/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQzMzgxLCJleHAiOjE3NDU3NDY5ODF9.yDRCIg0IhOvCMbJ98jGQ6_PBS3NrXY9rrJLGpnl2huw

###
// POST Data Lomba
POST http://localhost:5001/lomba
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQzMzgxLCJleHAiOjE3NDU3NDY5ODF9.yDRCIg0IhOvCMbJ98jGQ6_PBS3NrXY9rrJLGpnl2huw

{
    
    "lombaName": "Badminton"
}

###
// POST Data Category
POST http://localhost:5001/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQzMzgxLCJleHAiOjE3NDU3NDY5ODF9.yDRCIg0IhOvCMbJ98jGQ6_PBS3NrXY9rrJLGpnl2huw

{
    
    "categoryName": "Single Putr1",
    "lombaId": 1
}

###
//Update Lomba
PATCH http://localhost:5001/lomba/fe0beebe-95f9-4a9c-a4cc-dd50c95ec5d9
Content-Type: application/json

{
"lombaName": "test update"
}

###
//Update Category
PATCH http://localhost:5001/category/31c1ae12-1e2c-4176-a63d-9f6d4d53428f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQzMzgxLCJleHAiOjE3NDU3NDY5ODF9.yDRCIg0IhOvCMbJ98jGQ6_PBS3NrXY9rrJLGpnl2huw

{
"categoryName": "Single Putra"
}

###
//Delete Lomba
DELETE http://localhost:5001/lomba/4e535098-77d0-4dbb-a323-884aca705c97

###
//Delete Category
DELETE http://localhost:5001/category/485abb31-e7f2-4e60-b2f2-8ba32422cffc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM5OTMzLCJleHAiOjE3NDU3NDM1MzN9.3U9I_biKm71GWTVDLFieoGncgevAa0TIqHa4zipkCV4

###
//Category By Lomba
GET http://localhost:5001/category/lomba/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQzMzgxLCJleHAiOjE3NDU3NDY5ODF9.yDRCIg0IhOvCMbJ98jGQ6_PBS3NrXY9rrJLGpnl2huw

###
// Get All Dashboard
GET http://localhost:5001/Dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzYyMDI2LCJleHAiOjE3NDU3NjU2MjZ9.78R3OPKIN4g8yzTD_6q-8ZENxNNHAuJ-rfstxZitXxA

###
// Get Single Dashboard
GET http://localhost:5001/dashboard/112973ca-e0e2-4d00-b14c-acc63256cc8f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM1ODY1LCJleHAiOjE3NDU3Mzk0NjV9.NOCFiMg6B290z5L-1dEHHMSsJhv8iOhoEHwPjeb2LnY

###
// POST Data Dashboard
POST http://localhost:5001/Dashboard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzYyMDI2LCJleHAiOjE3NDU3NjU2MjZ9.78R3OPKIN4g8yzTD_6q-8ZENxNNHAuJ-rfstxZitXxA

{
    "lombaId": "1",
    "imageUrl": "1720496226573-437123357.jpg",
    "categoryId": "1",
    "aturanLomba": "<p>tesst </p>"
}

###
//Update Data Dashboard
PATCH http://localhost:5001/Dashboard/ae1ce55d-8065-489e-8b96-c54e61f7974d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQzMzgxLCJleHAiOjE3NDU3NDY5ODF9.yDRCIg0IhOvCMbJ98jGQ6_PBS3NrXY9rrJLGpnl2huw

{

    "lombaId": 1,
    "imageUrl": "1720883725343-69949999.jpg",
    "categoryId": 1,
    "aturanLomba": "tesst updated 2"
}

###
//Delete Data Dashboard
DELETE http://localhost:5001/Dashboard/e488f864-13f6-4d31-aed8-5a5a595954e2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzQyNDk1LCJleHAiOjE3NDU3NDYwOTV9.p7jxX7-ceyxVuT_w-f2Fi9bS-IfGji4vFHXDtCHfVoE

###
// Get All Banner
GET http://localhost:5001/Banner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM5OTMzLCJleHAiOjE3NDU3NDM1MzN9.3U9I_biKm71GWTVDLFieoGncgevAa0TIqHa4zipkCV4

###
// Get Single banner
GET http://localhost:5001/banner/a94420e0-9e7d-4ea9-afe3-605b60cc88aa


###
// POST Data Banner
POST http://localhost:5001/Banner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM5OTMzLCJleHAiOjE3NDU3NDM1MzN9.3U9I_biKm71GWTVDLFieoGncgevAa0TIqHa4zipkCV4

{

    "bannerName": "test 4",
    "imageBanner": "1720496226573-437123357.jpg"
}

###
// Update Data Banner
PATCH http://localhost:5001/banner/6c92e5d2-c361-4225-a168-91650721ef21
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM5OTMzLCJleHAiOjE3NDU3NDM1MzN9.3U9I_biKm71GWTVDLFieoGncgevAa0TIqHa4zipkCV4

{

    "bannerName": "test 1",
    "imageBanner": "1720962936493-392516406.jpg"
}

###
//Delete Data Banner
DELETE http://localhost:5001/Banner/6c92e5d2-c361-4225-a168-91650721ef21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NzM4MjMyLCJleHAiOjE3NDU3NDE4MzJ9.vm3IOHZK9KL1HJR4YO8QOGZe-160JJShBfO0mX4Qavw

###
// Get All Dokumentasi
GET http://localhost:5001/Dokumentasi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NjgwNDkwLCJleHAiOjE3NDU2ODQwOTB9.J_zA63gzriAvrRFZ3Lh0vC_trGC6WADNrscwf3O9zcQ

###
// Get Single Dokumentasi
GET http://localhost:5001/Dokumentasi/92223f36-7b5b-4500-ae84-2324025f8eee


###
// POST Data Dokumentasi
POST http://localhost:5001/Dokumentasi
Content-Type: application/json

{

    "kegiatanName": "test 3",
    "imageKegiatan": "1720496226573-437123357.jpg"
}

###
//Delete Data Dokuemntasi
DELETE http://localhost:5001/Dokumentasi/f03e3889-8615-409c-a641-c64c5829028e

###
// Get All Tentang Kegiatan
GET http://localhost:5001/TentangKegiatan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1NjgwNDkwLCJleHAiOjE3NDU2ODQwOTB9.J_zA63gzriAvrRFZ3Lh0vC_trGC6WADNrscwf3O9zcQ

###
// Get Single TentangKegiatan
GET http://localhost:5001/TentangKegiatan/114f1f91-fd8b-4490-9752-cfdc1abbda17


###
// POST Data TentangKegiatan
POST http://localhost:5001/TentangKegiatan
Content-Type: application/json

{

    "judulKegiatan": "test 1",
    "image": "1720496226573-437123357.jpg",
    "tanggal": "12/07/2024",
    "keterangan": "test"
}

###
//Delete Data TentangKegiatan
DELETE http://localhost:5001/TentangKegiatan/114f1f91-fd8b-4490-9752-cfdc1abbda17